In [8]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
%matplotlib inline
import risk_toolkit as rk
import numpy as np
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
hedge_fund_indices = rk.get_hf_returns()

C:\Users\pport\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '31/01/1997' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\pport\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '28/02/1997' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\pport\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '31/03/1997' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\pport\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '30/04/1997' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\pport\anaconda3\lib

In [10]:
rk.gaussian_var(hedge_fund_indices['2000':], level=1)

Convertible Arbitrage     0.034845
CTA Global                0.050336
Distressed Securities     0.031430
Emerging Markets          0.058070
Equity Market Neutral     0.014772
Event Driven              0.030853
Fixed Income Arbitrage    0.019519
Global Macro              0.024619
Long/Short Equity         0.039420
Merger Arbitrage          0.015355
Relative Value            0.021605
Short Selling             0.102130
Funds Of Funds            0.029385
dtype: float64

In [11]:
rk.gaussian_var(hedge_fund_indices['2000':], level=1, modified=True)

Convertible Arbitrage     0.103666
CTA Global                0.046643
Distressed Securities     0.049669
Emerging Markets          0.086796
Equity Market Neutral     0.041432
Event Driven              0.045732
Fixed Income Arbitrage    0.066479
Global Macro              0.022786
Long/Short Equity         0.051381
Merger Arbitrage          0.021282
Relative Value            0.048985
Short Selling             0.098323
Funds Of Funds            0.048793
dtype: float64

In [12]:
rk.historic_var(hedge_fund_indices['2000':], level=1)

Convertible Arbitrage     0.031674
CTA Global                0.050938
Distressed Securities     0.042642
Emerging Markets          0.065496
Equity Market Neutral     0.019800
Event Driven              0.038540
Fixed Income Arbitrage    0.030748
Global Macro              0.022632
Long/Short Equity         0.045060
Merger Arbitrage          0.022654
Relative Value            0.021788
Short Selling             0.107684
Funds Of Funds            0.027200
dtype: float64

#### Now let's get into portfolio optimization

In [13]:
ind = rk.get_ind_returns()

exp_return = rk.annualized_returns(ind['2013':'2017'], 12)

cov_matrix = ind['2013':'2017'].cov()

In [14]:
l = ['Books', 'Steel', 'Oil', 'Mines']

### The EW Portfolio

In [17]:
n_ew = exp_return[l].shape[0]

w_ew = np.repeat(1/n_ew, n_ew)

exp_return_ew = rk.portfolio_return(w_ew, exp_return[l])

w_ew

array([0.25, 0.25, 0.25, 0.25])

### The MSR

In [18]:
rk.max_sharpe_ratio(0.1, exp_return[l], cov_matrix.loc[l,l ])

array([4.51375048e-15, 1.00000000e+00, 1.40512602e-16, 0.00000000e+00])

In [19]:
exp_return[l]

Books    0.095312
Steel    0.100716
Oil      0.025275
Mines    0.005136
dtype: float64

### The GMV

In [20]:
rk.gmv(cov_matrix.loc[l, l])

array([4.77024870e-01, 4.33680869e-19, 4.34112024e-01, 8.88631053e-02])

In [21]:
exp_return[l]

Books    0.095312
Steel    0.100716
Oil      0.025275
Mines    0.005136
dtype: float64

In [24]:
rk.portfolio_vol(rk.max_sharpe_ratio(0.1, exp_return[l], cov_matrix.loc[l,l ]), ind['2018'][l].cov())

C:\Users\pport\AppData\Local\Temp\ipykernel_17504\734522384.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  rk.portfolio_vol(rk.max_sharpe_ratio(0.1, exp_return[l], cov_matrix.loc[l,l ]), ind['2018'][l].cov())


0.06346230747220709

In [ ]:
rk.portfolio_return()

In [23]:
rk.portfolio_vol(rk.gmv(cov_matrix.loc[l, l]), ind['2018'][l].cov())

C:\Users\pport\AppData\Local\Temp\ipykernel_17504\1715907813.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  rk.portfolio_vol(rk.gmv(cov_matrix.loc[l, l]), ind['2018'][l].cov())


0.054772453638838446

In [25]:
rk.annualized_volatility(ind['2018'][l], 12)

C:\Users\pport\AppData\Local\Temp\ipykernel_17504\3911268874.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  rk.annualized_volatility(ind['2018'][l], 12)


Books    0.183266
Steel    0.219840
Oil      0.252093
Mines    0.157180
dtype: float64